### ISSUE TITLE
No checkmarks for stock presets

### ISSUE THREAD

**Issue by jonheal** [liquidcitymotors/Via-for-VCVRack#18]
Hi.

Checkmarks do not appear next to selected items in the Stock Presets context sub-menu. Is that an issue with Rack's implementation of context menus?

Windows 10
Rack 1.0.5
Via 1.0.0

**Comment by SteveRussell33** [comment]
They're not fully implemented yet. Firmware and modules code is being refactored.

**Comment by liquidcitymotors** [comment]
Hi! 

@jonheal thanks for bringing this up.

@SteveRussell33 you are totally right we were focusing on some base level refactoring of the platform stuff and adding new modules.

No problem with Rack's submenu checkmarks; they had been intentionally omitted before because we tend to pick a preset then quickly wander. 

The checkmark now appears after selecting a preset, but disappears if you change any of the modes and "leave the preset", so to speak.
